### ISSUE TITLE
Select proper library for Opentracker

### ISSUE THREAD

**Issue by varlux** [geolink/opentracker-arduino-board#5]
I notice that if I have already installed DueFlashLibrary in the folder (LINUX OS) "/home/myname/Arduino/libraries/DueFlashStorage", Arduino's IDE automatically ignores the proper library in the folder "/home/myname/.arduino15/packages/opentracker/hardware/sam/1.0.4/libraries/DueFlashStorage".
Can I fix this issue without delete any directories in "Arduino/libraries"?
Thanks

**Comment by ppescher** [comment]
Not sure how the IDE deals with multiple versions of the same library. I thought that when a library is defined inside a board package, that version should be chosen because specific for that hardware. But Arduino developers might have thought differently.
You may try to increase the version of the library you want to be selected for build, by modifying the "library.properties" file (or vice-versa, decrease the version number of the one you don't want to use, depending on which one you prefer not to change).

**Comment by varlux** [comment]
mmm.....right, I thought to operate with #include directive....is it possible?

**Comment by ppescher** [comment]
I don't think so. Even if you used absolute paths inside the include directive, you would only cause the GCC preprocessor to use that particular header file (.h), but you would still need to force the compiler and linker to use the correct source/object file (.cpp/.o) that lives in the same folder.
This is something that the Arduino IDE does automatically, using some internal rules, when it sees an #include directive that references a possible library header file. The only way to use a different library would be to exploit those internal rules or to manually invoke arduino-builder with the proper libray paths.
I don't know what the rules are, but maybe a library in the user's profile takes precedence (inside your Documents/Arduino/libraries) and overrides default libraries (included in each board's package). So I don't know if the version trick works either.
